name: ⚡️ Run tests and typecheck before merge

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.16.x"

      - name: Install
        run: npm ci

      - name: Typecheck
        run: npm run type:check

      - name: Test
        run: npm run test
